version: '3.8'

services:
  kp-first-service:
    image: oski22/kp-first-service:2.0.0
    build:
      context: ./kp-first-service
    ports:
      - 8081:8081

  kp-first-composer:
    image: oski22/kp-first-composer:2.0.0
    build:
      context: ./kp-first-composer
    ports:
      - 8082:8082
    depends_on:
      - kp-first-service

  kp-second-service:
    image: oski22/kp-second-service:2.0.0
    build:
      context: ./kp-second-service
    ports:
      - 8083:8083

  kp-second-composer:
    image: oski22/kp-second-composer:2.0.0
    build:
      context: ./kp-second-composer
    ports:
      - 8084:8084
    depends_on:
      - kp-second-service